#!/usr/bin/env python3
"""
Runtime efficiency evaluation script for SMDA.

Compares reports generated by different versions (master vs upstream) to ensure
output consistency and compare execution times.
Uses caching for efficiency.

Usage: python evaluate_runtime.py

Output:
  - runtime_measurements/cache/evaluation.json: Full JSON comparison data
  - runtime_measurements/cache/evaluation.html: Human-readable HTML report
  - runtime_measurements/cache/*/cache.json: Per-folder precomputed data

Cache is only recomputed when file hashes change (manual update required).
"""

import hashlib
import json
import statistics
from datetime import datetime
from pathlib import Path

BASE_PATH = Path(__file__).resolve().parent.parent.parent.parent
RUNTIME_PATH = BASE_PATH / "runtime_measurements"
CACHE_PATH = RUNTIME_PATH / "cache"


# Version name mapping - rename pr_* and base_* for stability
def get_version_name(folder_name):
    """Map folder names to stable version identifiers."""
    if folder_name.startswith("pr_"):
        return "pr"
    elif folder_name.startswith("base_"):
        return "base"
    return folder_name


def compute_file_hash(filepath):
    """Compute SHA256 hash of a file."""
    sha256 = hashlib.sha256()
    with open(filepath, "rb") as f:
        for chunk in iter(lambda: f.read(8192), b""):
            sha256.update(chunk)
    return sha256.hexdigest()


def compute_five_num_summary(values):
    """Compute 5-number summary (min, Q1, median, Q3, max)."""
    if not values:
        return {"min": 0, "q1": 0, "median": 0, "q3": 0, "max": 0}
    sorted_vals = sorted(values)
    n = len(sorted_vals)
    return {
        "min": sorted_vals[0],
        "q1": statistics.median(sorted_vals[: n // 2]),
        "median": statistics.median(sorted_vals),
        "q3": statistics.median(sorted_vals[(n + 1) // 2 :]),
        "max": sorted_vals[-1],
    }


def parse_report(filepath):
    """Parse a single SMDA JSON report and extract precomputed values."""
    with open(filepath) as f:
        data = json.load(f)

    xcfg = data.get("xcfg", {})
    total_insns = 0
    func_counts = {}
    for addr, func_data in xcfg.items():
        blocks = func_data.get("blocks", {})
        if isinstance(blocks, dict):
            num_insns = sum(len(ins_list) for ins_list in blocks.values())
        else:
            num_insns = sum(len(ins_list) for ins_list in blocks)
        func_counts[addr] = num_insns
        total_insns += num_insns

    exec_time = data.get("execution_time", 0)

    return {
        "function_count": len(func_counts),
        "instruction_counts": func_counts,
        "total_instructions": total_insns,
        "execution_time": exec_time,
        "functions_per_sec": len(func_counts) / exec_time if exec_time > 0 else 0,
        "instructions_per_sec": total_insns / exec_time if exec_time > 0 else 0,
        "file_hash": compute_file_hash(filepath),
    }


def get_cache_key(folder_name):
    """Generate cache file path for a folder."""
    return CACHE_PATH / folder_name / "cache.json"


def load_from_cache(folder_name):
    """Load precomputed data from cache if valid."""
    cache_file = get_cache_key(folder_name)
    if cache_file.exists():
        try:
            with open(cache_file) as f:
                return json.load(f)
        except (OSError, json.JSONDecodeError):
            pass
    return None


def cache_reports(folder_name):
    """Cache reports for a folder if not already cached or stale."""
    folder_path = RUNTIME_PATH / folder_name
    cache_file = get_cache_key(folder_name)

    cached = load_from_cache(folder_name)
    if cached is not None:
        # Check if all files still match their cached hashes
        all_valid = True
        for filename, cached_info in cached.items():
            filepath = folder_path / filename
            if not filepath.exists():
                all_valid = False
                break
            if compute_file_hash(filepath) != cached_info.get("file_hash", ""):
                all_valid = False
                break
        if all_valid:
            return cached

    # Parse and cache all reports
    cache_data = {}
    for json_file in folder_path.glob("*.smda"):
        filename = json_file.name
        cache_data[filename] = parse_report(json_file)

    # Save cache
    cache_file.parent.mkdir(parents=True, exist_ok=True)
    with open(cache_file, "w") as f:
        json.dump(cache_data, f, indent=2)

    return cache_data


def compare_reports(head_data, version_data, head_label, version_label):
    """
    Compare parsed reports between head and version.

    Returns comparison results dict.
    """
    results = {
        "head_folder": head_label,
        "version_folder": version_label,
        "head_label_stable": get_version_name(head_label),
        "version_label_stable": get_version_name(version_label),
        "total_head_files": len(head_data),
        "total_version_files": len(version_data),
        "common_files": sorted(set(head_data.keys()) & set(version_data.keys())),
        "only_in_head": sorted(set(head_data.keys()) - set(version_data.keys())),
        "only_in_version": sorted(set(version_data.keys()) - set(head_data.keys())),
        "function_count_matches": [],
        "function_count_mismatches": [],
        "address_mismatches": [],
        "execution_times": {"head": [], "version": []},
        "throughput": {
            "head_functions_per_sec": [],
            "head_instructions_per_sec": [],
            "version_functions_per_sec": [],
            "version_instructions_per_sec": [],
        },
    }

    for filename in results["common_files"]:
        head_info = head_data[filename]
        version_info = version_data[filename]

        # Compare function counts
        if head_info["function_count"] == version_info["function_count"]:
            results["function_count_matches"].append(filename)
        else:
            results["function_count_mismatches"].append(
                {
                    "file": filename,
                    "head_function_count": head_info["function_count"],
                    "version_function_count": version_info["function_count"],
                }
            )

        # Compare instruction counts per address
        head_addrs = set(head_info["instruction_counts"].keys())
        version_addrs = set(version_info["instruction_counts"].keys())

        if head_addrs != version_addrs:
            results["address_mismatches"].append(
                {
                    "file": filename,
                    "only_in_head": sorted(head_addrs - version_addrs),
                    "only_in_version": sorted(version_addrs - head_addrs),
                }
            )
        else:
            count_diffs = {
                addr: {
                    "head": head_info["instruction_counts"][addr],
                    "version": version_info["instruction_counts"][addr],
                }
                for addr in head_addrs
                if head_info["instruction_counts"][addr] != version_info["instruction_counts"][addr]
            }
            if count_diffs:
                results["address_mismatches"].append({"file": filename, "instruction_count_diffs": count_diffs})

        results["execution_times"]["head"].append(head_info["execution_time"])
        results["execution_times"]["version"].append(version_info["execution_time"])
        results["throughput"]["head_functions_per_sec"].append(head_info.get("functions_per_sec", 0))
        results["throughput"]["head_instructions_per_sec"].append(head_info.get("instructions_per_sec", 0))
        results["throughput"]["version_functions_per_sec"].append(version_info.get("functions_per_sec", 0))
        results["throughput"]["version_instructions_per_sec"].append(version_info.get("instructions_per_sec", 0))

    # Calculate medians (more robust against outliers)
    if results["execution_times"]["head"]:
        results["execution_times"]["median_head"] = statistics.median(results["execution_times"]["head"])
    if results["execution_times"]["version"]:
        results["execution_times"]["median_version"] = statistics.median(results["execution_times"]["version"])

    # Calculate means for comparison
    if results["execution_times"]["head"]:
        results["execution_times"]["avg_head"] = statistics.mean(results["execution_times"]["head"])
    if results["execution_times"]["version"]:
        results["execution_times"]["avg_version"] = statistics.mean(results["execution_times"]["version"])

    if "median_head" in results["execution_times"] and "median_version" in results["execution_times"]:
        results["execution_times"]["diff_median"] = (
            results["execution_times"]["median_head"] - results["execution_times"]["median_version"]
        )

    if "avg_head" in results["execution_times"] and "avg_version" in results["execution_times"]:
        results["execution_times"]["diff_avg"] = (
            results["execution_times"]["avg_head"] - results["execution_times"]["avg_version"]
        )

    if (
        "median_head" in results["execution_times"]
        and "median_version" in results["execution_times"]
        and results["execution_times"]["median_version"] > 0
    ):
        results["execution_times"]["speedup_percent"] = (
            (results["execution_times"]["median_version"] - results["execution_times"]["median_head"])
            / results["execution_times"]["median_version"]
            * 100
        )

    # Calculate throughput medians and 5-number summaries
    if results["throughput"]["head_functions_per_sec"]:
        results["throughput"]["median_head_functions_per_sec"] = statistics.median(
            results["throughput"]["head_functions_per_sec"]
        )
        results["throughput"]["median_version_functions_per_sec"] = statistics.median(
            results["throughput"]["version_functions_per_sec"]
        )
        results["throughput"]["median_head_instructions_per_sec"] = statistics.median(
            results["throughput"]["head_instructions_per_sec"]
        )
        results["throughput"]["median_version_instructions_per_sec"] = statistics.median(
            results["throughput"]["version_instructions_per_sec"]
        )
        # Add 5-number summaries for throughput analysis
        results["throughput"]["five_num_head_functions_per_sec"] = compute_five_num_summary(
            results["throughput"]["head_functions_per_sec"]
        )
        results["throughput"]["five_num_version_functions_per_sec"] = compute_five_num_summary(
            results["throughput"]["version_functions_per_sec"]
        )
        results["throughput"]["five_num_head_instructions_per_sec"] = compute_five_num_summary(
            results["throughput"]["head_instructions_per_sec"]
        )
        results["throughput"]["five_num_version_instructions_per_sec"] = compute_five_num_summary(
            results["throughput"]["version_instructions_per_sec"]
        )

    return results


def generate_markdown_report(all_results, output_path):
    """Generate Markdown report from comparison results."""
    head_times = []
    version_times = []
    for result in all_results:
        head_times.extend(result["execution_times"]["head"])
        version_times.extend(result["execution_times"]["version"])

    head_label = result["head_label_stable"] if all_results else "pr"
    version_label = result["version_label_stable"] if all_results else "base"

    head_med = statistics.median(head_times) if head_times else 0
    version_med = statistics.median(version_times) if version_times else 0
    diff = head_med - version_med
    pct_change = (diff / version_med) * 100 if version_med > 0 else 0

    md = f"""### 📊 SMDA Performance Evaluation Benchmark Results
*Generated on: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}*

#### Summary Overview
| Metric | {version_label} (Base) | {head_label} (PR) | Change |
| --- | --- | --- | --- |
| **Files Processed** | {len(version_times)} | {len(head_times)} | - |
| **Median Execution Time** | {version_med:.4f}s | {head_med:.4f}s | {diff:+.4f}s ({pct_change:+.2f}%) |
| **Overall Throughput** | ~{(len(version_times) * 1000) / sum(version_times) if version_times and sum(version_times) > 0 else 0:.0f} func/s | ~{(len(head_times) * 1000) / sum(head_times) if head_times and sum(head_times) > 0 else 0:.0f} func/s | - |

#### Detailed Comparison
| Comparison Run | {head_label} Files | {version_label} Files | Common | Function Count Matches | Med {head_label} (s) | Med {version_label} (s) | Med Diff (s) | Speedup % |
| --- | --- | --- | --- | --- | --- | --- | --- | --- |
"""
    for result in all_results:
        head_folder = result["head_folder"]
        version_folder = result["version_folder"]
        head_count = len(result["execution_times"]["head"])
        version_count = len(result["execution_times"]["version"])
        common_count = len(result["common_files"])
        match_count = len(result["function_count_matches"])

        h_med = result["execution_times"].get("median_head", 0)
        v_med = result["execution_times"].get("median_version", 0)
        d_med = result["execution_times"].get("diff_median", 0)
        speedup = result["execution_times"].get("speedup_percent", 0)

        md += f"| {head_folder} vs {version_folder} | {head_count} | {version_count} | {common_count} | {match_count}/{common_count} | {h_med:.4f}s | {v_med:.4f}s | {d_med:+.4f}s | {speedup:+.2f}% |\n"

        if result["function_count_mismatches"] or result["address_mismatches"]:
            md += "\n⚠️ **Correctness Mismatches Detected:**\n"
            for m in result["function_count_mismatches"][:5]:
                md += f"- `{m['file']}`: function count mismatch (Base: {m['version_function_count']}, PR: {m['head_function_count']})\n"
            for m in result["address_mismatches"][:5]:
                md += f"- `{m['file']}`: function address set mismatch\n"
            if len(result["function_count_mismatches"]) > 5 or len(result["address_mismatches"]) > 5:
                md += "- ... (some mismatches truncated)\n"

    with open(output_path, "w") as f:
        f.write(md)

    return output_path


def generate_html_report(all_results, output_path):
    """Generate HTML report from comparison results."""
    html = (
        """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SMDA Runtime Efficiency Evaluation</title>
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; margin: 40px; background: #f5f5f5; }
        h1 { color: #333; border-bottom: 2px solid #4CAF50; padding-bottom: 10px; }
        h2 { color: #555; margin-top: 30px; }
        .summary { background: white; padding: 20px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); margin-bottom: 20px; }
        .summary h3 { margin-top: 0; color: #4CAF50; }
        table { width: 100%; border-collapse: collapse; background: white; margin-bottom: 20px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); border-radius: 8px; overflow: hidden; }
        th, td { padding: 12px 15px; text-align: left; border-bottom: 1px solid #ddd; }
        th { background: #4CAF50; color: white; font-weight: 600; }
        tr:hover { background: #f5f5f5; }
        .mismatch { color: #d32f2f; font-weight: 500; }
        .stats { display: flex; gap: 20px; flex-wrap: wrap; margin-top: 20px; }
        .stat-card { background: white; padding: 20px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); min-width: 200px; }
        .stat-card h4 { margin: 0 0 10px 0; color: #666; font-size: 14px; text-transform: uppercase; }
        .stat-value { font-size: 24px; font-weight: bold; color: #333; }
        .footer { margin-top: 40px; color: #888; font-size: 14px; text-align: center; }
    </style>
</head>
<body>
    <h1>SMDA Runtime Efficiency Evaluation</h1>
    <p>Generated: """
        + datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        + """</p>
"""
    )

    # Summary section
    html += """    <div class="summary">
        <h3>Summary Overview</h3>
        <div class="stats">
"""

    # Calculate overall stats
    head_times = []
    version_times = []
    for result in all_results:
        head_times.extend(result["execution_times"]["head"])
        version_times.extend(result["execution_times"]["version"])

    head_label = result["head_label_stable"] if all_results else "pr"
    version_label = result["version_label_stable"] if all_results else "base"

    head_med = statistics.median(head_times) if head_times else 0
    version_med = statistics.median(version_times) if version_times else 0
    head_total = sum(head_times)
    version_total = sum(version_times)
    head_fps = (len(head_times) * 1000) / head_total if head_total > 0 else 0
    version_fps = (len(version_times) * 1000) / version_total if version_total > 0 else 0

    html += f"""            <div class="stat-card">
                <h4>{head_label} Files</h4>
                <div class="stat-value">{len(head_times)}</div>
            </div>
            <div class="stat-card">
                <h4>{version_label} Files</h4>
                <div class="stat-value">{len(version_times)}</div>
            </div>
            <div class="stat-card">
                <h4>Med {head_label} Time</h4>
                <div class="stat-value">{head_med:.4f}s</div>
            </div>
            <div class="stat-card">
                <h4>Med {version_label} Time</h4>
                <div class="stat-value">{version_med:.4f}s</div>
            </div>
            <div class="stat-card">
                <h4>Med Diff</h4>
                <div class="stat-value">{head_med - version_med:.4f}s</div>
            </div>
            <div class="stat-card">
                <h4>{head_label} Files/s</h4>
                <div class="stat-value">~{head_fps:.0f}</div>
            </div>
            <div class="stat-card">
                <h4>{version_label} Files/s</h4>
                <div class="stat-value">~{version_fps:.0f}</div>
            </div>
        </div>
    </div>
"""

    head_label = result["head_label_stable"] if all_results else "pr"
    version_label = result["version_label_stable"] if all_results else "base"

    html += f"""    <h2>Detailed Comparison</h2>
    <table>
        <thead>
            <tr>
                <th>Comparison</th>
                <th>{head_label} Files</th>
                <th>{version_label} Files</th>
                <th>Common</th>
                <th>Function Count Match</th>
                <th>Med {head_label} Time (s)</th>
                <th>Med {version_label} Time (s)</th>
                <th>Med Diff (s)</th>
                <th>Speedup %</th>
            </tr>
        </thead>
        <tbody>
"""

    for result in all_results:
        head_folder = result["head_folder"]
        version_folder = result["version_folder"]
        head_count = len(result["execution_times"]["head"])
        version_count = len(result["execution_times"]["version"])
        common_count = len(result["common_files"])
        match_count = len(result["function_count_matches"])

        head_med = result["execution_times"].get("median_head", 0)
        version_med = result["execution_times"].get("median_version", 0)
        diff = result["execution_times"].get("diff_median", 0)
        speedup = result["execution_times"].get("speedup_percent", 0)

        match_color = "green" if match_count == common_count else "red"

        html += f"""            <tr>
                <td>{head_folder} vs {version_folder}</td>
                <td>{head_count}</td>
                <td>{version_count}</td>
                <td>{common_count}</td>
                <td style="color: {match_color}">{match_count}/{common_count}</td>
                <td>{head_med:.4f}</td>
                <td>{version_med:.4f}</td>
                <td style="color: {"green" if diff < 0 else "red"}">{diff:+.4f}</td>
                <td style="color: {"green" if speedup > 0 else "red"}">{speedup:+.2f}%</td>
            </tr>
"""

    html += """        </tbody>
    </table>
"""

    html += """    <h2>Throughput Analysis (Functions per Second)</h2>
    <div class="summary">
        <h3>5-Number Summary</h3>
        <div class="stats">
"""

    seen_versions = set()
    for result in all_results:
        head_folder = result["head_folder"]
        version_folder = result["version_folder"]
        head_label = result["head_label_stable"]
        version_label = result["version_label_stable"]

        if head_label not in seen_versions and "five_num_head_functions_per_sec" in result["throughput"]:
            seen_versions.add(head_label)
            head_5num = result["throughput"]["five_num_head_functions_per_sec"]
            html += f"""            <div class="stat-card">
                <h4>{head_folder} ({head_label}) - Func/s</h4>
                <div class="stat-value">Min: {head_5num["min"]:.2f} | Q1: {head_5num["q1"]:.2f} | Med: {head_5num["median"]:.2f} | Q3: {head_5num["q3"]:.2f} | Max: {head_5num["max"]:.2f}</div>
            </div>
"""

        if version_label not in seen_versions and "five_num_version_functions_per_sec" in result["throughput"]:
            seen_versions.add(version_label)
            version_5num = result["throughput"]["five_num_version_functions_per_sec"]
            html += f"""            <div class="stat-card">
                <h4>{version_folder} ({version_label}) - Func/s</h4>
                <div class="stat-value">Min: {version_5num["min"]:.2f} | Q1: {version_5num["q1"]:.2f} | Med: {version_5num["median"]:.2f} | Q3: {version_5num["q3"]:.2f} | Max: {version_5num["max"]:.2f}</div>
            </div>
"""

    html += """        </div>
    </div>
"""

    html += f"""    <p class="footer">Evaluation script: evaluate_runtime.py | Runtime measurements: {RUNTIME_PATH}</p>
</body>
</html>
"""

    with open(output_path, "w") as f:
        f.write(html)

    return output_path


def main():
    """Main evaluation function."""
    print("=" * 80)
    print("SMDA Runtime Efficiency Evaluation")
    print("=" * 80)

    # Discover all folders
    if not RUNTIME_PATH.exists():
        print(f"Error: {RUNTIME_PATH} does not exist!")
        return

    head_folders = sorted([d.name for d in RUNTIME_PATH.iterdir() if d.is_dir() and d.name.startswith("pr_")])
    version_folders = sorted([d.name for d in RUNTIME_PATH.iterdir() if d.is_dir() and d.name.startswith("base_")])

    print(f"\nFound {len(head_folders)} pr_* folders: {', '.join(head_folders)}")
    print(f"Found {len(version_folders)} base_* folders: {', '.join(version_folders)}")

    if not head_folders:
        print("Error: No pr_* folders found!")
        return

    if not version_folders:
        print("Error: No base_* folders found!")
        return

    # CACHE ALL REPORTS FIRST
    print("\n" + "-" * 80)
    print("Caching reports...")
    print("-" * 80)

    all_caches = {}
    all_caches_throughput = {}
    for folder in head_folders + version_folders:
        print(f"  Processing {folder}...", end=" ")
        try:
            cache = cache_reports(folder)
            all_caches_throughput[folder] = {
                "total_functions": sum(r["function_count"] for r in cache.values()),
                "total_instructions": sum(r["total_instructions"] for r in cache.values()),
                "total_exec_time": sum(r["execution_time"] for r in cache.values()),
                "avg_functions_per_sec": statistics.mean([r["functions_per_sec"] for r in cache.values()])
                if cache
                else 0,
                "avg_instructions_per_sec": statistics.mean([r["instructions_per_sec"] for r in cache.values()])
                if cache
                else 0,
                "files_cached": len(cache),
            }
            print(f"{len(cache)} files cached")
            all_caches[folder] = cache
        except Exception as e:
            print(f"ERROR: {e}")

    # COMPARE ALL PAIRS
    print("\n" + "-" * 80)
    print("Comparing versions...")
    print("-" * 80)

    all_results = []

    for version_folder in version_folders:
        for head_folder in head_folders:
            head_label = get_version_name(head_folder)
            version_label = get_version_name(version_folder)
            print(f"\n  Comparing {version_folder} ({version_label}) vs {head_folder} ({head_label})...")

            head_data = all_caches[head_folder]
            version_data = all_caches[version_folder]

            results = compare_reports(head_data, version_data, head_label=head_folder, version_label=version_folder)

            all_results.append(results)

            # Print summary for this comparison
            common = len(results["common_files"])
            matches = len(results["function_count_matches"])
            print(f"    Common files: {common}, Function count matches: {matches}")
            if "median_head" in results["execution_times"] and "median_version" in results["execution_times"]:
                print(
                    f"    Median times: {head_label}={results['execution_times']['median_head']:.4f}s, "
                    f"{version_label}={results['execution_times']['median_version']:.4f}s, "
                    f"diff={results['execution_times']['diff_median']:+.4f}s"
                )

    # Generate outputs
    print("\n" + "-" * 80)
    print("Generating reports...")
    print("-" * 80)

    # Transform throughput summary to use stable version names
    stable_throughput = {}
    for folder, data in all_caches_throughput.items():
        stable_throughput[folder] = data

    # JSON output
    json_output = CACHE_PATH / "evaluation.json"
    full_output = {"comparisons": all_results, "throughput_summary": stable_throughput}
    with open(json_output, "w") as f:
        json.dump(full_output, f, indent=2)
    print(f"  JSON report: {json_output}")

    # HTML output
    html_output = CACHE_PATH / "evaluation.html"
    generate_html_report(all_results, html_output)
    print(f"  HTML report: {html_output}")

    # Markdown output
    md_output = CACHE_PATH / "evaluation.md"
    generate_markdown_report(all_results, md_output)
    print(f"  Markdown report: {md_output}")

    print("\n" + "=" * 80)
    print("Evaluation complete!")
    print("=" * 80)


if __name__ == "__main__":
    main()
