import logging
import os


class SmdaConfig:
    # keep this in sync with smda.__version__
    VERSION = "4.4.7"
    ESCAPER_DOWNWARD_COMPATIBILITY = "1.13.16"
    CONFIG_FILE_PATH = str(os.path.abspath(__file__))
    PROJECT_ROOT = str(os.path.abspath(os.sep.join([CONFIG_FILE_PATH, "..", "..", ".."])))

    ### An (optional) WinAPI database as generated by ApiScout (https://github.com/danielplohmann/apiscout)
    API_COLLECTION_FILES = {}
    ### global logging-config setup
    # Only do basicConfig if no handlers have been configured
    LOG_LEVEL = logging.INFO
    LOG_FORMAT = "%(asctime)-15s: %(name)-32s - %(message)s"

    ### SMDA disassembler config
    # cooperative budget in seconds for disassembly, polled between candidates and between
    # passes but never within one, so a run overshoots rather than being cut off; 0 disables it
    TIMEOUT = 300
    # maximum number of bytes to allocate while loading
    MAX_IMAGE_SIZE = 100 * 1024 * 1024
    # store raw binary buffer in SmdaReport to enable carving data from refs
    STORE_BUFFER = False
    # extract strings during disassembly
    WITH_STRINGS = False
    # the options named USE_*, RESOLVE_*, RECORD_*, CANDIDATE_QUEUE and HIGH_ACCURACY steer
    # recursive candidate discovery and are read by the intel and aarch64 backends only; the
    # cil and dalvik backends run their own analysis pipelines and ignore them
    # the queue to use for candidate management
    CANDIDATE_QUEUE = "PriorityQueue"  # choose from: ["BracketQueue", "PriorityQueue"]
    # improve disassembly by resolving references through data flows
    USE_ALIGNMENT = True
    USE_SYMBOLS_AS_CANDIDATES = True
    # seed AArch64 function candidates from the PE ARM64 exception directory (classic 0xAA64
    # images only); funclet/fragment records are filtered at seeding, and IDA-labeled ARM64
    # system binaries (wermgr/ping/robocopy/bcrypt) show equal-or-better boundary accuracy
    # with the directory enabled, so it is on by default
    USE_PE_ARM64_PDATA_CANDIDATES = True
    # force function-end splits at x64 PE .pdata RUNTIME_FUNCTION EndAddresses so that
    # SMDA functions align with the compiler's exception-table boundaries; off by default
    # because MSVC fragments single control-flow functions across many .pdata ranges
    # (cold/hot splitting), so naive splitting fragments real functions. When on, splits
    # are only performed where the interior .pdata start has a non-fall-through inbound
    # jmp/call from another recovered function, never from candidate membership alone.
    USE_PE_X64_PDATA_ENDS = False
    # promote unclaimed ELF .eh_frame FDE starts as late candidates on both instruction sets
    # (after the primary pass, before gap analysis); off until validated against ground-truth
    # function boundaries. Unwind ranges are not function starts by definition - .eh_frame also
    # covers ranges that are not independent functions - which is why this stays opt-in while
    # the Mach-O function-start table below does not
    USE_ELF_EH_FRAME_CANDIDATES = False
    # extend the AArch64 adr/adrp address-materialization scan to Mach-O instruction sections,
    # recording targets as weak address evidence; off until validated with exact-address ground
    # truth for the Mach-O corpus
    USE_MACHO_ADDRESS_REF_CANDIDATES = False
    # promote unclaimed Mach-O LC_FUNCTION_STARTS entries as late candidates (after the primary
    # pass, before gap analysis). The linker writes the table and stripping keeps it, and segment
    # file offsets and VM offsets coincide in Mach-O, so it also reads correctly out of a mapped
    # image - unlike a PE COFF symbol table. Across the bundled Mach-O fixtures it lifts the share
    # of linker-declared starts recovered from 87.4% to 96.7% (1884 -> 2083 of 2155) with no sample
    # losing a function; off until that is confirmed against ground-truth boundaries rather than
    # against the same table the pass consumes
    USE_MACHO_FUNCTION_STARTS = False
    RESOLVE_REGISTER_CALLS = True
    # resolve "call/jmp dword ptr [<reg> + <disp>]" against a runtime-built import table and
    # record the API plus the slot it lives in; annotation only, it books no code refs
    RESOLVE_COMPUTED_IMPORT_SLOTS = True
    # also record an API whose import slot is only loaded into a register, never called through
    # the slot itself - the shape a language runtime that dispatches its own syscalls produces.
    # Off by default: it widens an apiref from "calls this API" to "references this API".
    RECORD_IMPORT_SLOT_LOADS = False
    # limit this to avoid blowing up analysis time for weird samples
    MAX_INDIRECT_CALLS_PER_BASIC_BLOCK = 50
    # backstops against memory usage explosion during candidate identification on pathological/junk samples
    # maximum number of function candidates to track; 0 == unlimited. Normal binaries have orders of magnitude fewer.
    MAX_FUNCTION_CANDIDATES = 200000
    # maximum number of inbound call references tracked per candidate; 0 == unlimited. Bounds set growth and rescoring.
    MAX_CALL_REFS_PER_CANDIDATE = 2000
    # backstops for batch mode, where peak worker RSS scales with input size. The factor is
    # peak RSS per byte of input, measured at ~1.6x margin over an 8.1 MB sample; the fraction
    # is how much of the available memory (physical, or the cgroup limit where one applies)
    # the large-input pool may claim. Both are here rather than in BatchProcessor so an
    # operator can move them for a machine whose corpus does not look like the measured one.
    LARGE_INPUT_RSS_FACTOR = 500
    MEMORY_BUDGET_FRACTION = 0.5
    HIGH_ACCURACY = True
    # promote the targets of jumps that leave a function into functions of their own, in a
    # pass after gap analysis. Off by default: what it buys depends entirely on how much a
    # binary tail-calls, and it is never free. On libstdc++.so.6 it adds 337 functions
    # (8473 -> 8810) for 40-130% more analysis time depending on the machine; on Go ELF and
    # Mach-O memory images, 8 functions each for 20-26%. A jump into an already-recovered
    # function is still treated as a tailcall with the pass off - only the promotion of
    # not-yet-known targets needs it.
    RESOLVE_TAILCALLS = False
    # optional metadata generation options; the largest built-in performance lever.
    # Measured on the cutwail fixture, as a share of all Python calls per run: hashing 10.0%,
    # nesting 4.6%, SCC 3.2%, all three together 17.8%.
    CALCULATE_SCC = True
    CALCULATE_NESTING = True
    CALCULATE_HASHING = True
    # confidence score to use for filtering functions before including them in the output
    CONFIDENCE_THRESHOLD = 0.0

    def __init__(self):
        self.API_COLLECTION_FILES = dict(SmdaConfig.API_COLLECTION_FILES)
        self._disableLiefLogging()

    def _disableLiefLogging(self):
        # disable excessive logging from LIEF
        try:
            import lief

            lief.logging.disable()
        except ImportError:
            pass
