import logging
import os


class SmdaConfig:
    # keep this in sync with smda.__version__
    VERSION = "4.5.0"
    # Bump this whenever any architecture's InstructionEscaper changes its
    # output (mnemonic groups or escaped operands). Downstream indexes such as
    # MCRIT treat reports whose smda_version is below this value as stale.
    # Last output change: 4.4.5 (segment-qualified memory operands, AVX-512
    # registers, six mnemonic groups).
    ESCAPER_DOWNWARD_COMPATIBILITY = "4.4.5"
    CONFIG_FILE_PATH = str(os.path.abspath(__file__))
    PROJECT_ROOT = str(os.path.abspath(os.sep.join([CONFIG_FILE_PATH, "..", "..", ".."])))

    ### An (optional) WinAPI database as generated by ApiScout (https://github.com/danielplohmann/apiscout)
    API_COLLECTION_FILES = {}
    ### global logging-config setup
    # Only do basicConfig if no handlers have been configured
    LOG_LEVEL = logging.INFO
    LOG_FORMAT = "%(asctime)-15s: %(name)-32s - %(message)s"

    ### SMDA disassembler config
    # cooperative budget in seconds for disassembly, polled between candidates, between passes,
    # every 256 basic blocks within a function and between tailcall resolutions. The verdict
    # latches the first time it trips, so a function the budget cut short is not re-promoted
    # by a later pass; work already in flight still finishes, so a run overshoots rather than
    # being cut off; 0 disables it
    TIMEOUT = 300
    # maximum number of bytes to allocate while loading
    MAX_IMAGE_SIZE = 100 * 1024 * 1024
    # store raw binary buffer in SmdaReport to enable carving data from refs
    STORE_BUFFER = False
    # extract strings during disassembly
    WITH_STRINGS = False
    # the options named USE_*, RESOLVE_*, RECORD_*, CANDIDATE_QUEUE and HIGH_ACCURACY steer
    # recursive candidate discovery and are read by the intel and aarch64 backends only; the
    # cil and dalvik backends run their own analysis pipelines and ignore them
    # the queue to use for candidate management
    CANDIDATE_QUEUE = "PriorityQueue"  # choose from: ["BracketQueue", "PriorityQueue"]
    # improve disassembly by resolving references through data flows
    USE_ALIGNMENT = True
    USE_SYMBOLS_AS_CANDIDATES = True
    # seed AArch64 function candidates from the PE ARM64 exception directory (classic 0xAA64
    # images only); funclet/fragment records are filtered at seeding, and IDA-labeled ARM64
    # system binaries (wermgr/ping/robocopy/bcrypt) show equal-or-better boundary accuracy
    # with the directory enabled, so it is on by default
    USE_PE_ARM64_PDATA_CANDIDATES = True
    # do not read `bti j` as a function entry on AArch64. The four BTI forms are not
    # interchangeable: J permits a target reached by `br` - an indirect jump, which is what a
    # switch dispatch does to a case block - while C permits one reached by `blr`, which is how
    # a function is reached indirectly. A compiler that wrote `bti j` was naming an interior
    # label, and the hardware would fault a call landing on it. The prologue scan read all four
    # as entries, so every jump pad in the image was booked.
    # Measured on 72 built AArch64 ELF cells, attributing each prologue-sole booking to the arm
    # of `is_function_prologue` that accepted it: `bti j` produced 803 false positives and 0 real
    # functions, `bti c` produced 0 false positives and 505 real functions. The split is exact,
    # not statistical, which is what distinguishes this from a threshold.
    # The ARM64 Mach-O corpus is not a control: 11 cells book no BTI-opened prologue candidate at
    # all, so the rule is inert there rather than confirmed. It reaches no other architecture -
    # the intel scan has no BTI shape - and it is deliberately not applied to the PE ARM64
    # exception-record reader, which accepts the same word through a different question and has
    # no corpus to be measured on - there is no ARM64 PE among the samples available here.
    USE_AARCH64_BTI_TARGET_TYPE = True
    # force function-end splits at x64 PE .pdata RUNTIME_FUNCTION EndAddresses so that
    # SMDA functions align with the compiler's exception-table boundaries; off by default
    # because MSVC fragments single control-flow functions across many .pdata ranges
    # (cold/hot splitting), so naive splitting fragments real functions. When on, splits
    # are only performed where the interior .pdata start has a non-fall-through inbound
    # jmp/call from another recovered function, never from candidate membership alone.
    USE_PE_X64_PDATA_ENDS = False
    # promote unclaimed ELF .eh_frame FDE starts as late candidates on both instruction sets
    # (after the primary pass, before gap analysis). Unwind ranges are not function starts by
    # definition - .eh_frame also covers ranges that are not independent functions. Measured
    # against symbol-table boundaries over 50 locally built gcc/clang ELF binaries (11384
    # labelled functions, analysed stripped): recall 93.79% -> 94.68%, so 101 more real starts,
    # against 56 more addresses landing strictly inside a labelled function body. Off by
    # default because that is a deliberate baseline move rather than a free win - one bundled
    # fixture changes - so enabling it belongs with a corpus run, not with a config edit
    USE_ELF_EH_FRAME_CANDIDATES = False
    # extend the AArch64 adr/adrp address-materialization scan to Mach-O instruction sections,
    # recording targets as weak address evidence; off until validated with exact-address ground
    # truth for the Mach-O corpus
    USE_MACHO_ADDRESS_REF_CANDIDATES = False
    # promote unclaimed Mach-O LC_FUNCTION_STARTS entries as late candidates (after the primary
    # pass, before gap analysis). The linker writes the table and stripping keeps it, and segment
    # file offsets and VM offsets coincide in Mach-O, so it also reads correctly out of a mapped
    # image - unlike a PE COFF symbol table. Scored against the corpus samples' own symbol tables
    # instead of the table this pass consumes, with symbols-as-candidates forced off so the metric
    # is independent: recall 97.99% -> 98.74% of 1985 symbol-declared starts, 15 more recovered
    # and 5 fewer functions that no symbol names. Off by default because it moves 5 of the 12
    # Mach-O corpus samples, all upwards - a deliberate baseline update, not a config edit
    USE_MACHO_FUNCTION_STARTS = False
    RESOLVE_REGISTER_CALLS = True
    # resolve "call/jmp dword ptr [<reg> + <disp>]" against a runtime-built import table and
    # record the API plus the slot it lives in; annotation only, it books no code refs
    RESOLVE_COMPUTED_IMPORT_SLOTS = True
    # also record an API whose import slot is only loaded into a register, never called through
    # the slot itself - the shape a language runtime that dispatches its own syscalls produces.
    # Off by default: it widens an apiref from "calls this API" to "references this API".
    RECORD_IMPORT_SLOT_LOADS = False
    # limit this to avoid blowing up analysis time for weird samples
    MAX_INDIRECT_CALLS_PER_BASIC_BLOCK = 50
    # backstops against memory usage explosion during candidate identification on pathological/junk samples
    # maximum number of function candidates to track; 0 == unlimited. Normal binaries have orders of magnitude fewer.
    MAX_FUNCTION_CANDIDATES = 200000
    # maximum number of inbound call references tracked per candidate; 0 == unlimited. Bounds set growth and rescoring.
    MAX_CALL_REFS_PER_CANDIDATE = 2000
    # backstops for batch mode, where peak worker RSS scales with input size. The factor is
    # peak RSS per byte of input, measured at ~1.6x margin over an 8.1 MB sample; the fraction
    # is how much of the available memory (physical, or the cgroup limit where one applies)
    # the large-input pool may claim. Both are here rather than in BatchProcessor so an
    # operator can move them for a machine whose corpus does not look like the measured one.
    LARGE_INPUT_RSS_FACTOR = 500
    MEMORY_BUDGET_FRACTION = 0.5
    HIGH_ACCURACY = True
    # promote the targets of jumps that leave a function into functions of their own, in a
    # pass after gap analysis. Off by default, and measurement says keep it that way: against
    # symbol-table boundaries over 50 locally built gcc/clang ELF binaries it recovers 70 more
    # real starts but adds 235 addresses strictly inside a labelled function body, so it breaks
    # real functions apart faster than it finds new ones. It is also never free - on
    # libstdc++.so.6 it adds 337 functions (8473 -> 8810) for 40-130% more analysis time
    # depending on the machine; on Go ELF and Mach-O memory images, 8 functions each for 20-26%.
    # A jump into an already-recovered function is still treated as a tailcall with the pass
    # off - only the promotion of not-yet-known targets needs it.
    RESOLVE_TAILCALLS = False
    # optional metadata generation options; the largest built-in performance lever.
    # Measured on the cutwail fixture, as a share of all Python calls per run: hashing 10.0%,
    # nesting 4.6%, SCC 3.2%, all three together 17.8%.
    CALCULATE_SCC = True
    CALCULATE_NESTING = True
    CALCULATE_HASHING = True
    # confidence score to use for filtering functions before including them in the output
    CONFIDENCE_THRESHOLD = 0.0

    def __init__(self):
        self.API_COLLECTION_FILES = dict(SmdaConfig.API_COLLECTION_FILES)
        self._disableLiefLogging()

    def _disableLiefLogging(self):
        # disable excessive logging from LIEF
        try:
            import lief

            lief.logging.disable()
        except ImportError:
            pass
